### ISSUE TITLE
이 행사에 대한 소개를 어디서 볼 수 있을까요?

### ISSUE THREAD

**Issue by roeniss** [saengmotmi/future_conf_4th_participants#1]
우연히 https://future-conf-4th-participants.pages.dev/ 링크를 얻어서 어떤 이벤트인지 궁금해졌는데, 행사 소개를 못찾아서 헤매고 있습니다. 그러다가 여기가 그나마 주최자님께 근접한 수단인 것 같아 이슈를 남기게 되었습니다.

퓨처콘 4th 에 대한 정보를 어디서 알 수 있을까요?

원래 외부에 공개되지 않는 것이 행사 의도라면, 이 이슈를 삭제해주시면 감사하겠습니다.

**Comment by saengmotmi** [comment]
@roeniss https://www.linkedin.com/in/jong-taek-oh-8b29901a7/ 이쪽으로 연락 주시면 메시지로 설명드리겠습니다!
